In [61]:
import pandas as pd
import seaborn as sb
from sklearn.datasets import load_digits
import warnings
warnings.filterwarnings('ignore')

In [76]:
data=load_digits()

In [77]:
data.images.shape

(1797, 8, 8)

In [78]:
data.images[0]

array([[ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.],
       [ 0.,  0., 13., 15., 10., 15.,  5.,  0.],
       [ 0.,  3., 15.,  2.,  0., 11.,  8.,  0.],
       [ 0.,  4., 12.,  0.,  0.,  8.,  8.,  0.],
       [ 0.,  5.,  8.,  0.,  0.,  9.,  8.,  0.],
       [ 0.,  4., 11.,  0.,  1., 12.,  7.,  0.],
       [ 0.,  2., 14.,  5., 10., 12.,  0.,  0.],
       [ 0.,  0.,  6., 13., 10.,  0.,  0.,  0.]])

In [80]:
df=data.images.reshape(len(data.images),-1)

In [38]:
df.dtype

dtype('float64')

In [39]:
df[0]

array([ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
       15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
       12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
        0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
       10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.])

In [40]:
df[0].shape

(64,)

In [41]:
df.shape

(1797, 64)

Scaling Data

In [42]:
df.min()

0.0

In [43]:
df.max()

16.0

In [45]:
df/=10

In [46]:
df[0]

array([0. , 0. , 0.5, 1.3, 0.9, 0.1, 0. , 0. , 0. , 0. , 1.3, 1.5, 1. ,
       1.5, 0.5, 0. , 0. , 0.3, 1.5, 0.2, 0. , 1.1, 0.8, 0. , 0. , 0.4,
       1.2, 0. , 0. , 0.8, 0.8, 0. , 0. , 0.5, 0.8, 0. , 0. , 0.9, 0.8,
       0. , 0. , 0.4, 1.1, 0. , 0.1, 1.2, 0.7, 0. , 0. , 0.2, 1.4, 0.5,
       1. , 1.2, 0. , 0. , 0. , 0. , 0.6, 1.3, 1. , 0. , 0. , 0. ])

In [47]:
from sklearn.model_selection import train_test_split

In [50]:
data

{'data': array([[0. , 0. , 0.5, ..., 0. , 0. , 0. ],
        [0. , 0. , 0. , ..., 1. , 0. , 0. ],
        [0. , 0. , 0. , ..., 1.6, 0.9, 0. ],
        ...,
        [0. , 0. , 0.1, ..., 0.6, 0. , 0. ],
        [0. , 0. , 0.2, ..., 1.2, 0. , 0. ],
        [0. , 0. , 1. , ..., 1.2, 0.1, 0. ]]),
 'target': array([0, 1, 2, ..., 8, 9, 8]),
 'frame': None,
 'feature_names': ['pixel_0_0',
  'pixel_0_1',
  'pixel_0_2',
  'pixel_0_3',
  'pixel_0_4',
  'pixel_0_5',
  'pixel_0_6',
  'pixel_0_7',
  'pixel_1_0',
  'pixel_1_1',
  'pixel_1_2',
  'pixel_1_3',
  'pixel_1_4',
  'pixel_1_5',
  'pixel_1_6',
  'pixel_1_7',
  'pixel_2_0',
  'pixel_2_1',
  'pixel_2_2',
  'pixel_2_3',
  'pixel_2_4',
  'pixel_2_5',
  'pixel_2_6',
  'pixel_2_7',
  'pixel_3_0',
  'pixel_3_1',
  'pixel_3_2',
  'pixel_3_3',
  'pixel_3_4',
  'pixel_3_5',
  'pixel_3_6',
  'pixel_3_7',
  'pixel_4_0',
  'pixel_4_1',
  'pixel_4_2',
  'pixel_4_3',
  'pixel_4_4',
  'pixel_4_5',
  'pixel_4_6',
  'pixel_4_7',
  'pixel_5_0',
  'pixel_5_1',
 

In [51]:
x_train,x_test,y_train,y_test=train_test_split(df,data.target)

In [52]:
x_train

array([[0. , 0. , 0. , ..., 1.6, 1.1, 0. ],
       [0. , 0.2, 1.2, ..., 1.5, 0.3, 0. ],
       [0. , 0. , 1. , ..., 0.1, 0. , 0. ],
       ...,
       [0. , 0. , 0.9, ..., 0.3, 0. , 0. ],
       [0. , 0. , 0.5, ..., 0.3, 0. , 0. ],
       [0. , 0. , 1. , ..., 1.1, 1.4, 0.1]])

In [53]:
y_train

array([6, 2, 0, ..., 0, 8, 2])

In [54]:
from sklearn.linear_model import LogisticRegression

In [55]:
model=LogisticRegression()

In [62]:
model.fit(x_train,y_train)

LogisticRegression()

In [63]:
y_predict=model.predict(x_test)

In [74]:
from sklearn.metrics import r2_score,mean_absolute_error,mean_absolute_percentage_error,accuracy_score,confusion_matrix,classification_report

In [65]:
r2_score(y_test,y_predict)

0.9289116208894519

In [66]:
mean_absolute_error(y_test,y_predict)

0.12

In [67]:
mean_absolute_percentage_error(y_test,y_predict)

50039995859672.195

In [68]:
from sklearn.ensemble import RandomForestClassifier

In [69]:
model1=RandomForestClassifier()

In [70]:
model1.fit(x_train,y_train)

RandomForestClassifier()

In [71]:
y1_predict=model1.predict(x_test)

In [73]:
accuracy_score(y_test,y1_predict)

0.9844444444444445

In [81]:
confusion_matrix(y_test,y_predict)

array([[48,  0,  0,  0,  0,  1,  0,  0,  0,  0],
       [ 0, 49,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1, 41,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 39,  0,  1,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 40,  0,  0,  0,  0,  1],
       [ 0,  0,  1,  1,  0, 50,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 36,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 44,  0,  1],
       [ 0,  2,  1,  1,  0,  1,  0,  0, 44,  0],
       [ 0,  0,  0,  1,  0,  0,  0,  0,  0, 46]], dtype=int64)

In [83]:
print(classification_report(y_test,y_predict))

              precision    recall  f1-score   support

           0       1.00      0.98      0.99        49
           1       0.94      1.00      0.97        49
           2       0.95      0.98      0.96        42
           3       0.93      0.97      0.95        40
           4       1.00      0.98      0.99        41
           5       0.94      0.96      0.95        52
           6       1.00      1.00      1.00        36
           7       1.00      0.98      0.99        45
           8       1.00      0.90      0.95        49
           9       0.96      0.98      0.97        47

    accuracy                           0.97       450
   macro avg       0.97      0.97      0.97       450
weighted avg       0.97      0.97      0.97       450

